name: DevSecOps Pipeline

on:
    push:
        branches: ["**"]
    pull_request:
        branches: ["**"]
    workflow_call:
        inputs:
            run_semgrep:
                description: "Rodar Semgrep?"
                required: false
                default: true
                type: boolean
            run_trufflehog:
                description: "Rodar TruffleHog?"
                required: false
                default: true
                type: boolean
            run_depscan:
                description: "Rodar DepScan?"
                required: false
                default: true
                type: boolean

jobs:
    semgrep:
        name: Run Semgrep (Security Scan)
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Python (for Semgrep)
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"

            - name: Install Semgrep
              run: pip install semgrep

            - name: Run Semgrep scan
              run: semgrep scan --config "p/owasp-top-ten" --error

    trufflehog-scan:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Download TruffleHog v3 binary
              run: |
                  curl -L -o trufflehog.tar.gz https://github.com/trufflesecurity/trufflehog/releases/download/v3.72.0/trufflehog_3.72.0_linux_amd64.tar.gz
                  tar -xzf trufflehog.tar.gz
                  chmod +x trufflehog
                  sudo mv trufflehog /usr/local/bin/
            - name: Run TruffleHog scan
              run: trufflehog filesystem --json .trufflehog-ignore.txt .

    depscan:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: ">=3.8"

            - name: Install OWASP DepScan
              run: pip install owasp-depscan

            - name: Run DepScan
              run: |
                  depscan --src . --reports-dir ./reports

            - name: Upload report
              uses: actions/upload-artifact@v4
              with:
                  name: depscan-report
                  path: reports

    scc-metrics:
        name: SCC Metrics
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Baixar e instalar o SCC
              run: |
                  wget -qO scc.tar.gz https://github.com/boyter/scc/releases/latest/download/scc_Linux_x86_64.tar.gz
                  sudo tar xf scc.tar.gz -C /usr/local/bin scc
                  rm -f scc.tar.gz
            - name: Run SCC scan
              run: scc --by-file --languages go,python,javascript,typescript --no-complexity
